# Generated by Django 4.0.5 on 2022-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('reports_category_name', models.CharField(max_length=102, unique=True)),
            ],
            options={
                'db_table': 'table_reports_category',
            },
        ),
    ]
