# Generated by Django 4.0.5 on 2022-06-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('type_code', models.CharField(max_length=102, unique=True)),
                ('key_code', models.CharField(max_length=102, unique=True)),
                ('value_code', models.CharField(max_length=102, unique=True)),
            ],
            options={
                'db_table': 'table_allcode',
            },
        ),
        migrations.AlterField(
            model_name='reports',
            name='reports_name',
            field=models.CharField(max_length=102, unique=True),
        ),
    ]
