# Generated by Django 4.0.5 on 2022-06-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reports_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports_Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('month_name', models.CharField(max_length=102, unique=True)),
                ('quarter', models.CharField(max_length=102)),
            ],
            options={
                'db_table': 'table_month',
            },
        ),
    ]
