# Generated by Django 4.0.5 on 2022-06-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reports_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports_Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('day', models.CharField(max_length=102)),
                ('year', models.CharField(max_length=102)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_month', to='reports.reports_month')),
            ],
            options={
                'db_table': 'table_date',
            },
        ),
    ]
