# Generated by Django 4.0.5 on 2022-06-22 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reports_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports_Departments',
            new_name='Departments',
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('industry_name', models.CharField(max_length=102, unique=True)),
                ('departments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='reports.departments')),
            ],
            options={
                'db_table': 'table_industry',
            },
        ),
    ]
