# Generated by Django 4.0.5 on 2022-06-22 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_products_category_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports_Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('total_including_tax', models.CharField(max_length=99)),
                ('total_excluding_tax', models.CharField(max_length=99)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_date', to='reports.reports_date')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_products', to='reports.products')),
                ('reports', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_reports', to='reports.reports')),
            ],
            options={
                'db_table': 'table_reports_revenue',
            },
        ),
    ]
