# Generated by Django 4.0.5 on 2022-06-23 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_allcode_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='products_category',
        ),
        migrations.DeleteModel(
            name='Products_Category',
        ),
    ]
