# Generated by Django 4.0.5 on 2022-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_remove_allcode_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcode',
            name='table_name',
            field=models.CharField(default='', max_length=102),
        ),
    ]
